// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jGvfSglGNOKcbn9iTC2Ug4a_q-ab2gI',
    appId: '1:41160719092:web:42fa0822176ffecf463ca1',
    messagingSenderId: '41160719092',
    projectId: 'check-in-7ecd7',
    authDomain: 'check-in-7ecd7.firebaseapp.com',
    storageBucket: 'check-in-7ecd7.appspot.com',
    measurementId: 'G-3JV5EZHQ6E',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArLxMF1wjbQzOw4xIqh_zfNJ8-cG7CaBY',
    appId: '1:41160719092:android:c706181dfebd457e463ca1',
    messagingSenderId: '41160719092',
    projectId: 'check-in-7ecd7',
    storageBucket: 'check-in-7ecd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QKaerf5i4Mj0PN52-zhfZ8kQ6hcgz3Q',
    appId: '1:41160719092:ios:246b5db2c7526c37463ca1',
    messagingSenderId: '41160719092',
    projectId: 'check-in-7ecd7',
    storageBucket: 'check-in-7ecd7.appspot.com',
    iosClientId:
        '41160719092-sdkcvbdqcrci7lso8p83nrnpkvt89dqc.apps.googleusercontent.com',
    iosBundleId: 'com.developlogix.checkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2QKaerf5i4Mj0PN52-zhfZ8kQ6hcgz3Q',
    appId: '1:41160719092:ios:246b5db2c7526c37463ca1',
    messagingSenderId: '41160719092',
    projectId: 'check-in-7ecd7',
    storageBucket: 'check-in-7ecd7.appspot.com',
    iosClientId:
        '41160719092-sdkcvbdqcrci7lso8p83nrnpkvt89dqc.apps.googleusercontent.com',
    iosBundleId: 'com.developlogix.checkin',
  );
}
